### ISSUE TITLE
Problem about the frequency with which robot car refreshes the camera image

### ISSUE THREAD

**Issue by zhouxuan009** [zhouxuan009/CS179J-Team07#7]
Hi, 

In the collision avoidance part, the car will move forward or spin for only 0.001s and then it refresh the card. In your code, the time of moving forward or spinning is 0.5s. Should we create a parameter for it and set the parameter to a low value like 0.001s to make the camera fresh with a high frequency ?

Thank you!

**Comment by ctsan005** [comment]
Currently, I set it to 0.5s is to keep it safe. Because the car needs to first avoid the obstacle by spinning to either left or right, then move straight for 0.5s, then recalculate the angle from the destination and spin again. I worry if we get the exact angle that it identifies as not blocked, and move straight with it, it might need to readjust multiple times until it passed the obstacle.  But this highly dependent on how wide the angle of the camera.  Should able to decrease the time a bit to get a faster response, but need some testing on what number works the best.

**Comment by zhouxuan009** [comment]
I find a problem in the previous code. forward() Sleep(0.5) doesn't mean the robot car go forward 0.5s. It will still move forward utill its moving status is updated

**Comment by ctsan005** [comment]
The sleep(0.5) is not intended to stop the car, it just to prevent it from updating to another movement. So the sleep(0.5) is to keep the car to move forward for at least 0.5 sec, which can be longer, depending on what does the camera gives back.
